version: '3.6'

services:

    # Backend API
    smart-face-api:
        container_name: backend
        build: ./ #composes using this image
        command: npm start #command run in the container
        working_dir: /usr/src/smart-face-api
        environment: 
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-face-docker
            POSTGRES_HOST: postgres
            REDIS_URI: redis://redis:6379
        ports:
            - "3000:3000" #forwards localhost:3000 to 3000
        volumes:
            - ./:/usr/src/smart-face-api
    
    # Postgres
    postgres:
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-face-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - "5431:5432"
    
    # Redis
    redis:
        image: redis
        ports:
        - "6378:6379"
    
